<?php

use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
/**
* Run the database seeds.
*
* @return void
*/
public function run()
{
    $ciudades = [
        'BELLO',
        'CACERES',
        'CALDAS',
        'CARMEN DE VIVORAL',
        'CAUCASIA',
        'COPACABANA',
        'DON MATIAS',
        'EL JARDIN',
        'EL POBLADO',
        'EL RETIRO',
        'ENVIGADO',
        'GIRARDOTA',
        'GUARNE ',
        'ITAGUI',
        'LA CEJA',
        'LA ESTRELLA',
        'MARINILLA',
        'MEDELLIN',
        'PTO BERRIO',
        'PTO VALDIVIA',
        'RIONEGRO',
        'SABANETA',
        'SAN ANTONIO DE PEREIRA',
        'SANTA ROSA DE OSOS',
        'SANTUARIO',
        'TARAZA',
        'YONDO',
        'ARAUCA',
        'ARAUQUITA',
        'CARANAL',
        'FORTUL',
        'LA ESMERALDA',
        'PANAMA',
        'PTO NARIÑO',
        'PTO RONDON',
        'PUEBLO NUEVO',
        'SARAVENA',
        'TAME',
        'BARANOA ',
        'BARRANQUILLA',
        'GALAPA',
        'LURUACO ',
        'PTO COLOMBIA',
        'SOLEDAD',
        'MALANBO',
        'SABANA GRANDE ',
        'SABANALARGA ',
        'SANTO TOMAS ',
        'ARJONA',
        'CARTAGENA',
        'SAN JACINTO ',
        'SANTA CATALINA',
        'TURBACO',
        'CARMEN DE BOLIVAR ',
        'MAGANGUE',
        'SAN JUAN NEPOMUCENO',
        'AQUITANIA',
        'BELEN',
        'BELENCITO ',
        'BOAVITA',
        'BOYACA',
        'CERINZA',
        'CHINAVITA',
        'CHIQUINQUIRA',
        'CHISCAS ',
        'CHITA',
        'CORRALES',
        'CUBARA',
        'CUCAITA ',
        'CUITIVA',
        'DUITAMA',
        'EL COCUY ',
        'EL CRUCERO',
        'EL ESPINO',
        'FIRAVITOBA',
        'GAMESA ',
        'GARAGOA (B)',
        'GUACAMAYAS (B)',
        'GUATEQUE (B)',
        'GUICAN (B)',
        'IZA',
        'JENESANO',
        'LA CAPILLA',
        'LA UVITA ',
        'MACANAL ',
        'MIRAFLORES ',
        'MONGUI',
        'MONIQUIRA',
        'NOBSA ',
        'NUEVO COLON ',
        'PAEZ',
        'PAIPA ',
        'PAJARITO',
        'PANQUEBA ',
        'PAZ DEL RIO',
        'PESCA ',
        'PTO BOYACA',
        'RAMIRIQUI',
        'RAQUIRA ',
        'SABOYÁ ',
        'SACHICA ',
        'SAMACA ',
        'SAN JOSE DE PARE ',
        'SAN L DE GACENO',
        'SAN MATEO',
        'SANTA MARIA ',
        'SANTA ROSA DE VITERBO',
        'SANTANA',
        'SOATA',
        'SOCHA',
        'SOCOTA',
        'SOGAMOSO',
        'SORA',
        'SORACA',
        'SOTAQUIRA ',
        'SUSACON',
        'SUTAMARCHAN ',
        'TASCO',
        'TENZA',
        'TIBANA ',
        'TIBASOSA',
        'TINJACÁ ',
        'TIPACOQUE ',
        'TOPAGA',
        'TOTA',
        'TUNJA',
        'TUTA',
        'UMBITA',
        'VENTAQUEMADA ',
        'VILLA DE LEIVA ',
        'ZETAQUIRA ',
        'CHINCHINA',
        'GUARINOCITO',
        'LA DORADA',
        'MANIZALES',
        'VILLAMARIA ',
        'FLORENCIA ',
        'AGUAZUL',
        'ARAGUANEY',
        'HATO COROZAL',
        'LA CHAPARRERA',
        'MANI ',
        'MONTERREY',
        'NUNCHIA',
        'OROCUE',
        'PAZ ARIPORO',
        'PORE',
        'SAN L PALANQUE',
        'TAMARA',
        'TAURAMENA',
        'TRINIDAD',
        'VILLA CAROLA',
        'VILLANUEVA',
        'YOPAL',
        'CALOTO',
        'EL BORDO ',
        'MONDOMO ',
        'PIENDAMO',
        'POPAYAN',
        'PTO TEJADA ',
        'SDER DE QUILICHAO',
        'TIMBIO ',
        'TUNIA',
        'VILLA RICA',
        'AGUACHICA',
        'AGUSTIN CODAZZI',
        'BECERRIL ',
        'BESOTE',
        'BOSCONIA',
        'CALENTURITA',
        'CARBONERA',
        'CHIRIGUANA ',
        'CODAZZI',
        'CURUMANI',
        'EL BURRO',
        'EL COPEY ',
        'LA DRUMMO',
        'LA ESPERANZA ',
        'LA FLORESTA',
        'LA GLORIA',
        'LA JAGUA DE IBIRICO',
        'LA LOMA CALENTURITAS',
        'LA MATA',
        'LA PAZ',
        'PAILITAS',
        'PELAYA',
        'SAN ALBERTO',
        'SAN DIEGO',
        'SAN MARTIN',
        'SAN ROQUE',
        'VALLEDUPAR',
        'CERETE',
        'CHINU ',
        'CIENAGA DE ORO',
        'LORICA',
        'MONTELIBANO',
        'MONTERIA',
        'PLANETA RICA',
        'PUEBLO NUEVO ',
        'SAHAGUN',
        'ALBAN ',
        'ANAPOIMA ',
        'APULO ',
        'ARBELAEZ',
        'BOGOTA',
        'BOJACÁ ',
        'BRICEÑO',
        'CAJICA ',
        'CAPARRAPI',
        'CAQUEZA',
        'CHIA',
        'CHINAUTA ',
        'CHIPAQUE',
        'CHOCONTA ',
        'COTA',
        'EL ROSAL ',
        'FACATATIVA',
        'FOMEQUE',
        'FUNZA',
        'FUSAGASUGA',
        'GACHANCIPA',
        'GIRARDOT',
        'GRANADA ',
        'GUADUAS',
        'GUAGUERO',
        'GUAYAVETAL',
        'LA CALERA',
        'LA MESA',
        'LA VEGA ',
        'LENGUAZAQUE',
        'LIMONCITO',
        'MACHETA ',
        'MADRID',
        'MAYA ',
        'MESITAS',
        'MOSQUERA',
        'NEMOCON',
        'NEUSA',
        'PANDI',
        'PARATEBUENO',
        'PTO SALGAR',
        'PUENE QUETAME',
        'SAN BERNARDO',
        'SAN RAIMUNDO',
        'SASAIMA',
        'SESQUILÉ',
        'SIBATÉ',
        'SILVANIA ',
        'SIMIJACA ',
        'SOPO',
        'SUBACHOQUE',
        'SUBIA',
        'SUESCA',
        'SUSA',
        'SUTATAUSA',
        'TABIO',
        'TAUSA',
        'TENJO',
        'TOCAIMA',
        'TOCANCIPÁ',
        'UBATE',
        'UNE',
        'VENECIA',
        'VILLA PINZON ',
        'VILLETA',
        'ZIPAQUIRÁ',
        'ALBANIA ',
        'FONSECA',
        'HATO NUEVO',
        'MAICAO',
        'PTO  BOLIVAR',
        'RIOACHA',
        'SAN JUAN DE CESAR',
        'URIBIA',
        'URUMITA ',
        'VILLANUEVA',
        'BARRANCAS ',
        'LA JAGUA DEL PILAR',
        'SAN JOSE DEL GUAVIARE',
        'AIPE ',
        'ALTAMIRA ',
        'CAMPOALEGRE ',
        'EL QUIMBO',
        'GARZON (H)',
        'GIGANTE (H)',
        'GUADALUPE (H)',
        'HOBO ',
        'LA PLATA ',
        'NEIVA',
        'PITALITO ',
        'RIVERA ',
        'SUAZA ',
        'TESALIA',
        'TIMANÁ ',
        'ARACATACA',
        'CIENAGA',
        'EL RETEN ',
        'FUNDACION',
        'SANTA MARTA',
        'ACACIAS',
        'BARRANCA DE UPIA',
        'CASTILLA ',
        'CUBARRAL',
        'CUMARAL',
        'FUENTE DE ORO',
        'GRANADA',
        'GUAMAL',
        'POMPEYA',
        'PTO CONCORDIA',
        'PTO GAITAN',
        'PTO LLERAS',
        'PTO LOPEZ',
        'RESTREPO',
        'RUBIALES',
        'SAN MARTIN',
        'VILLAVICENCIO',
        'IPIALES',
        'PASTO',
        'TUMACO',
        'CHINACOTA',
        'CUCUTA',
        'GIBRALTAR',
        'OCAÑA',
        'PAMPLONA',
        'SAMORE',
        'SAN BERNARDO DE BATA',
        'ALCALA ',
        'ARMENIA',
        'CALARCA',
        'LA TEBAIDA',
        'MONTENEGRO',
        'QUIMBAYA ',
        'CERRITOS',
        'DOS QUEBRADAS',
        'LA VIRGINIA ',
        'PEREIRA',
        'SANTA ROSA DE CABAL',
        'ARATOCA ',
        'BARBOSA',
        'BARRANCABERMEJA',
        'BUCARAMANGA',
        'CAPITANEJO',
        'CHARALA',
        'CHITARAQUE',
        'CIMITARRA',
        'CURITÌ ',
        'FLORIDA BLANCA',
        'GIRON',
        'GÜEPSA (S)',
        'LANDAZURI',
        'LEBRIJA',
        'MALAGA',
        'OIBA ',
        'PESCADERO',
        'PIE DE CUESTA',
        'PLAYON',
        'PTE NACIONAL ',
        'PUERTO WILCHES',
        'RIONEGRO',
        'SABANA DE TORRES',
        'SAN GIL',
        'SAN JOSE DE MIRANDA ',
        'SOCORRO ',
        'SUAITA',
        'VADO REAL ',
        'VARICHARA',
        'VELEZ',
        'VILLANUEVA',
        'COROZAL ',
        'COVEÑAS',
        'OVEJAS',
        'SAMPUES',
        'SINCELEJO',
        'TOLU',
        'TOLU VIEJO',
        'ALVARADO',
        'ARMERO',
        'CAJAMARCA',
        'CAMBAO',
        'CHICORAL ',
        'ESPINAL',
        'FLANDES ',
        'FRESNO ',
        'GUALANDDAY',
        'GUAMO',
        'HONDA',
        'IBAGUE',
        'LERIDA',
        'LIBANO',
        'MARIQUITA ',
        'MELGAR',
        'NATAGAIMA ',
        'PRADO',
        'PURIFICACION',
        'SALDAÑA ',
        'VENADILLO',
        'ANDALUCIA',
        'BUENAVENTURA',
        'BUGA',
        'BUGA LA GRANDE',
        'CAICEDONIA',
        'CALI',
        'CANDELARIA',
        'CARTAGO',
        'DAGUA',
        'EL CERRITO ',
        'EL PLACER ',
        'FLORIDA ',
        'GINEBRA (V)',
        'GUACARÍ (V)',
        'JAMUNDI',
        'LA PAILA ',
        'LA UNION ',
        'LA URIBE ',
        'LA VICTORIA ',
        'LOBOGUERRERO',
        'OBANDO ',
        'PALMIRA',
        'PRADERA ',
        'ROLDANILLO ',
        'ROZO ',
        'SAN PEDRO ',
        'SEVILLA ',
        'SONSO',
        'TORO ',
        'TULUA',
        'VIJES ',
        'VILLA GORGONA ',
        'YOTOCO',
        'YUMBO',
        'ZARZAL '
    ];
    $departamentos = [

        'ANTIOQUIA',
        'ARAUCA',
        'ATLANTICO ',
        'BOLIVAR',
        'BOYACA',
        'CALDAS',
        'CAQUETA',
        'CASANARE',
        'CAUCA',
        'CESAR',
        'CORDOBA',
        'CUNDINAMARCA',
        'GUAJIRA',
        'GUAVIARE',
        'HUILA',
        'MAGDALENA',
        'META',
        'NARIÑO',
        'NTE DE SANTANDER',
        'QUINDIO',
        'RISARALDA',
        'SANTANDER',
        'SUCRE',
        'TOLIMA',
        'VALLE DE CAUCA',

    ];
    $indice = [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        6,
        6,
        6,
        6,
        6,
        7,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        9,
        9,
        9,
        9,
        9,
        9,
        9,
        9,
        9,
        9,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        11,
        11,
        11,
        11,
        11,
        11,
        11,
        11,
        11,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        12,
        13,
        13,
        13,
        13,
        13,
        13,
        13,
        13,
        13,
        13,
        13,
        13,
        14,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        15,
        16,
        16,
        16,
        16,
        16,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        17,
        18,
        18,
        18,
        19,
        19,
        19,
        19,
        19,
        19,
        19,
        20,
        20,
        20,
        20,
        20,
        20,
        21,
        21,
        21,
        21,
        21,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        22,
        23,
        23,
        23,
        23,
        23,
        23,
        23,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25,
        25
    ];
    $dias = [

        24,
        48,
        24,
        48,
        48,
        36,
        48,
        48,
        24,
        48,
        24,
        24,
        48,
        24,
        48,
        24,
        48,
        24,
        24,
        48,
        48,
        24,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        72,
        48,
        72,
        72,
        24,
        24,
        72,
        48,
        48,
        72,
        72,
        48,
        72,
        48,
        72,
        48,
        72,
        72,
        48,
        72,
        72,
        48,
        72,
        48,
        48,
        24,
        24,
        72,
        72,
        24,
        72,
        24,
        72,
        72,
        48,
        48,
        24,
        48,
        24,
        72,
        48,
        72,
        48,
        48,
        72,
        72,
        72,
        72,
        48,
        72,
        48,
        48,
        72,
        72,
        48,
        24,
        24,
        72,
        72,
        24,
        24,
        72,
        48,
        48,
        36,
        72,
        24,
        24,
        24,
        24,
        24,
        72,
        72,
        72,
        48,
        24,
        72,
        48,
        48,
        24,
        24,
        24,
        24,
        72,
        24,
        48,
        72,
        72,
        24,
        24,
        72,
        48,
        48,
        24,
        24,
        72,
        24,
        24,
        72,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        72,
        72,
        24,
        24,
        24,
        72,
        24,
        24,
        24,
        24,
        24,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        72,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        24,
        36,
        36,
        36,
        24,
        24,
        24,
        24,
        36,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        48,
        24,
        72,
        24,
        24,
        48,
        24,
        24,
        24,
        36,
        24,
        24,
        24,
        36,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        36,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        36,
        24,
        24,
        24,
        96,
        72,
        72,
        96,
        72,
        72,
        96,
        96,
        96,
        96,
        96,
        72,
        48,
        24,
        48,
        24,
        48,
        24,
        24,
        24,
        24,
        48,
        24,
        48,
        24,
        24,
        48,
        48,
        96,
        72,
        72,
        72,
        72,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        48,
        24,
        48,
        24,
        24,
        48,
        24,
        24,
        48,
        48,
        96,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        48,
        24,
        72,
        48,
        24,
        48,
        24,
        24,
        24,
        24,
        48,
        48,
        72,
        24,
        24,
        24,
        48,
        24,
        48,
        48,
        48,
        24,
        72,
        24,
        48,
        24,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        72,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        48,
        48,
        48,
        48,
        48,
        24,
        48,
        24,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        48,
        24,
        48
    ];

    foreach ($departamentos as $key => $departamento) {

        DB::table('departaments')->insert([
            'name' => $departamento
        ]);	
    }
    foreach ($ciudades as $key => $ciudad) {

        DB::table('cities')->insert([
            'departament_id' => $indice[$key],
            'name' => $ciudad,
            'dias_envio' => $dias[$key],
        ]);	
    }

}
}
